# Generated by Django 4.2.7 on 2023-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=50)),
                ('bse_ticker', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('nse_ticker', models.CharField(default='', max_length=10, null=True)),
                ('moq', models.IntegerField(choices=[(0, 'Quarterly'), (1, 'Monthly')], default=0)),
            ],
        ),
    ]
