# Generated by Django 4.2.7 on 2023-11-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_alter_company_bse_ticker_alter_company_nse_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='moq',
        ),
    ]
