# Generated by Django 4.2.7 on 2023-12-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0004_remove_company_nse_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cur_quarter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='cur_year',
            field=models.IntegerField(default=0),
        ),
    ]
