# Generated by Django 4.2.7 on 2023-12-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0005_company_cur_quarter_company_cur_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='a_quarter',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='a_year',
            field=models.JSONField(default=list),
        ),
    ]
