# Generated by Django 4.2.7 on 2023-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0006_company_a_quarter_company_a_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
