# Generated by Django 4.2.7 on 2023-12-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0008_alter_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='a_quarter',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_year',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cur_quarter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cur_year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
