# Generated by Django 4.2.7 on 2023-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0009_alter_company_a_quarter_alter_company_a_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='a_quarter',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='a_year',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cur_quarter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cur_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
