# Generated by Django 4.2.7 on 2023-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0010_alter_company_a_quarter_alter_company_a_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bse_ticker',
            field=models.CharField(default='ID', max_length=15, primary_key=True, serialize=False),
        ),
    ]
