# Generated by Django 4.2.7 on 2023-12-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0012_pdf_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdf_Data',
        ),
    ]
