# Generated by Django 4.2.7 on 2023-12-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0016_pdf_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_Data',
        ),
    ]
