# Generated by Django 4.2.7 on 2023-12-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0018_pdf_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='pdf_data',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='retrieval.company'),
        ),
    ]
