# Generated by Django 4.2.7 on 2023-12-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retrieval', '0020_remove_pdf_data_ticker_delete_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=1000)),
                ('bse_ticker', models.CharField(default='ID', max_length=15, primary_key=True, serialize=False)),
                ('cur_year', models.IntegerField(blank=True, default=0, null=True)),
                ('cur_quarter', models.IntegerField(blank=True, default=0, null=True)),
                ('a_year', models.JSONField(blank=True, default=list, null=True)),
                ('a_quarter', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1', models.JSONField(blank=True, default=list, null=True)),
                ('pdf3', models.JSONField(blank=True, default=list, null=True)),
                ('pdf2', models.JSONField(blank=True, default=list, null=True)),
                ('pdf4', models.JSONField(blank=True, default=list, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrieval.company')),
            ],
        ),
    ]
