# Generated by Django 4.2.7 on 2023-12-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0021_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_Data',
        ),
    ]
